# Generated by Django 5.0.1 on 2024-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_taught',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_taught1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_taught2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
