# Generated by Django 5.0.2 on 2024-03-17 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='labs',
            field=models.ManyToManyField(to='timetable.lab'),
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('lab', models.CharField(max_length=100)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.class')),
            ],
        ),
    ]
