# Generated by Django 5.0.2 on 2024-03-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_lab_class_labs_timetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.lab'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.subject'),
        ),
    ]
